# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'swiftdemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'Alamofire'
pod 'Kingfisher'
pod 'AlamofireImage'
pod 'MJRefresh'
pod 'JLRoutes'

end
